In [1]:
import json
import pandas as pd
import os

In [2]:
list_data = ['route_data', 'package_data', 'travel_times', 'actual_sequences']
path = 'almrrc2021-data-training/model_build_inputs/'

with open(path + 'route_data.json', 'r') as f:
    route_data = json.load(f)

with open(path + 'package_data.json', 'r') as f:
    package_data = json.load(f)

with open(path + 'travel_times.json', 'r') as f:
    travel_times = json.load(f)

with open(path + 'actual_sequences.json', 'r') as f:
    actual_sequences = json.load(f)

In [3]:
len(route_data), len(package_data), len(travel_times), len(actual_sequences)

(6112, 6112, 6112, 6112)

In [4]:
first_route = list(route_data.keys())[0]
first_route in package_data and first_route in travel_times and first_route in actual_sequences

True

In [5]:
routes_list = []
route_data[first_route].keys()

dict_keys(['station_code', 'date_YYYY_MM_DD', 'departure_time_utc', 'executor_capacity_cm3', 'route_score', 'stops'])

In [6]:
routes_list = []

for route_id, route_info in route_data.items():
    routes_list.append({
        'route_id': route_id,
        'station_code': route_info['station_code'],
        'date': route_info['date_YYYY_MM_DD'],
        'departure_time_utc': route_info['departure_time_utc'],
        'executor_capacity_cm3': route_info['executor_capacity_cm3'],
        'route_score': route_info['route_score']
    })

routes_df = pd.DataFrame(routes_list)
routes_df.head(4)

,route_id,station_code,date,departure_time_utc,executor_capacity_cm3,route_score
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,3313071.0,High
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,4247527.0,High
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,4247527.0,High
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,3313071.0,High

In [7]:
routes_df.shape

(6112, 6)

In [8]:
stops_list = []
for route_id, route_info in route_data.items():
    stops = route_info['stops']
    for stop_id, stop_info in stops.items():
        
        stops_list.append({
            'route_id': route_id,
            'stop_id': stop_id,
            'lat': stop_info["lat"],
            'lng': stop_info["lng"],
            "type": stop_info["type"],
            'zone_id': stop_info["zone_id"]})

stops_df = pd.DataFrame(stops_list)
stops_df.head(4)

,route_id,stop_id,lat,lng,type,zone_id
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AD,34.099611,-118.283062,Dropoff,P-12.3C
1,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AF,34.101587,-118.291125,Dropoff,A-1.2D
2,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AG,34.089727,-118.285530,Dropoff,A-2.1A
3,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,BA,34.096132,-118.292869,Dropoff,A-1.2C

In [9]:
stops_df.shape

(904527, 6)

In [10]:
package_data[first_route]

packages_list = []

for route_id, route_info in package_data.items():
    for stop_id, stop_info in route_info.items():
        for package_id, package_info in stop_info.items():

            packages_list.append({
                'route_id': route_id,
                'stop_id': stop_id,
                'package_id': package_id,
                'scan status': package_info['scan_status'],
                'start_time_utc':package_info['time_window']['start_time_utc'],
                'end_time_utc':package_info['time_window']['end_time_utc'],
                'planned_service_time_seconds': package_info['planned_service_time_seconds'],
                'depth_cm': package_info['dimensions']['depth_cm'],
                'height_cm': package_info['dimensions']['height_cm'],
                'width_cm': package_info['dimensions']['width_cm']})

packages_df = pd.DataFrame(packages_list)
packages_df.head(4)

,route_id,stop_id,package_id,scan status,start_time_utc,end_time_utc,planned_service_time_seconds,depth_cm,height_cm,width_cm
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AD,PackageID_9d7fdd03-f2cf-4c6f-9128-028258fc09ea,DELIVERED,NaN,NaN,59.3,25.4,7.6,17.8
1,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AD,PackageID_5541e679-b7bd-4992-b288-e862f6c84ae7,DELIVERED,2018-07-27 16:00:00,2018-07-28 00:00:00,59.3,25.4,12.7,17.8
2,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AD,PackageID_84d0295b-1adb-4a33-a65e-f7d6247c7a07,DELIVERED,NaN,NaN,59.3,39.4,7.6,31.8
3,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AF,PackageID_15c6a204-ec5f-4ced-9c3d-472316cc7759,DELIVERED,2018-07-27 16:00:00,2018-07-28 00:00:00,27.0,30.0,3.0,27.4

In [11]:
actual_sequences

sequences_list = []

for route_id, route_info in actual_sequences.items():
    actual = route_info['actual']
    for stop_id, stop_order in actual.items():
        sequences_list.append({
            'route_id': route_id,
            'stop_id': stop_id,
            'stop_order': stop_order})

sequences_df = pd.DataFrame(sequences_list)

sequences_df.head(4)

                                       route_id stop_id  stop_order
0  RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AD         105
1  RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AF          47
2  RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AG           4
3  RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      BA          33

In [12]:
sequences_df

                                            route_id stop_id  stop_order
0       RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AD         105
1       RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AF          47
2       RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      AG           4
3       RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      BA          33
4       RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77      BE         109
...                                              ...     ...         ...
904522  RouteID_fffd257c-3041-4736-be7a-5efea8af1173      YU         145
904523  RouteID_fffd257c-3041-4736-be7a-5efea8af1173      YW           4
904524  RouteID_fffd257c-3041-4736-be7a-5efea8af1173      ZK          45
904525  RouteID_fffd257c-3041-4736-be7a-5efea8af1173      ZS          84
904526  RouteID_fffd257c-3041-4736-be7a-5efea8af1173      ZX           3

[904527 rows x 3 columns]

In [13]:
sequences_sorted = sequences_df.sort_values(['route_id', 'stop_order']).copy()
sequences_df.sort_values(['route_id', 'stop_order']).copy()

sequences_sorted['next_stop_id'] = (
    sequences_sorted.groupby('route_id')['stop_id'].shift(-1))

legs_df = (sequences_sorted.dropna(subset=['next_stop_id'])
    .rename(columns={'stop_id': 'from_stop', 'next_stop_id': 'to_stop'})
    [['route_id', 'from_stop', 'to_stop', 'stop_order']]
    .copy())

legs_df.head()

,route_id,from_stop,to_stop,stop_order
103,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,VE,TG,0
89,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,TG,GP,1
31,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,GP,HT,2
40,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,HT,AG,3
2,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AG,QM,4

In [14]:
def get_travel_time(row):
    route_id = row['route_id']
    from_stop = row['from_stop']
    to_stop = row['to_stop']
    return travel_times[route_id][from_stop][to_stop]

legs_df['travel_time_seconds'] = legs_df.apply(get_travel_time, axis=1)

In [15]:
legs_df.head()

,route_id,from_stop,to_stop,stop_order,travel_time_seconds
103,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,VE,TG,0,1509.7
89,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,TG,GP,1,25.4
31,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,GP,HT,2,37.4
40,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,HT,AG,3,62.2
2,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,AG,QM,4,74.9

In [17]:
route_travel_duration = (legs_df.groupby('route_id')['travel_time_seconds']
    .sum().reset_index(name='total_travel_duration'))

route_service_time = (packages_df.groupby('route_id')['planned_service_time_seconds']
                      .sum().reset_index(name='total_service_time_duration'))

route_duration_df = route_travel_duration.merge(route_service_time,
                                             on='route_id',
                                             how='left')

route_duration_df['ERD_seconds'] = (route_duration_df['total_travel_duration']
                                    + route_duration_df['total_service_time_duration'])

route_duration_df['ERD_hours'] = route_duration_df["ERD_seconds"] / 3600

route_duration_df.sort_values('ERD_hours', ascending = False).head(4)

,route_id,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours
4021,RouteID_a99c1bfb-d13d-4173-9e0a-959d727f37ce,7977.9,30187.0,38164.9,10.601361
22,RouteID_00bea18c-ee16-4a18-a916-7a447c733a7d,9904.3,27170.3,37074.6,10.298500
2893,RouteID_7aaf509e-cf04-4ec1-9944-dc72b197d7c7,8313.9,26418.6,34732.5,9.647917
4397,RouteID_b92a1e1f-a850-48de-9f28-9f895921abb0,14375.1,20247.0,34622.1,9.617250

In [18]:
route_df = routes_df.merge(route_duration_df,
                           on='route_id', how='left')
route_df.head(4)

,route_id,station_code,date,departure_time_utc,executor_capacity_cm3,route_score,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,3313071.0,High,7754.1,12940.9,20695.0,5.748611
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,4247527.0,High,6647.8,18623.8,25271.6,7.019889
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,4247527.0,High,9897.4,18951.1,28848.5,8.013472
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,3313071.0,High,9491.5,15476.3,24967.8,6.935500

In [24]:
stops_df.head(4)

route_num_stops= (stops_df.groupby('route_id')['stop_id']
                  .count().reset_index(name='num_stops'))
route_df = route_df.merge(route_num_stops, on='route_id', how='left')
route_df.head(4)

,route_id,station_code,date,departure_time_utc,executor_capacity_cm3,route_score,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours,num_stops_x,num_stops_y,num_stops
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,3313071.0,High,7754.1,12940.9,20695.0,5.748611,119,119,119
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,4247527.0,High,6647.8,18623.8,25271.6,7.019889,106,106,106
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,4247527.0,High,9897.4,18951.1,28848.5,8.013472,128,128,128
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,3313071.0,High,9491.5,15476.3,24967.8,6.935500,142,142,142

In [27]:
packages_df.head(2)

route_packages = (packages_df.groupby('route_id')['package_id']
                  .count().reset_index(name='total_packages'))

route_df = route_df.merge(route_packages, on='route_id', how='left')
route_df.head(4)

,route_id,station_code,date,departure_time_utc,executor_capacity_cm3,route_score,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours,num_stops_x,num_stops_y,num_stops,total_packages
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,3313071.0,High,7754.1,12940.9,20695.0,5.748611,119,119,119,276
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,4247527.0,High,6647.8,18623.8,25271.6,7.019889,106,106,106,199
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,4247527.0,High,9897.4,18951.1,28848.5,8.013472,128,128,128,212
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,3313071.0,High,9491.5,15476.3,24967.8,6.935500,142,142,142,241

In [30]:
route_df['packages_per_stop'] = (route_df['total_packages'] / route_df['num_stops'])

route_df['avg_service_time'] = (
    route_df['total_service_time_duration'] / route_df['total_packages'])

route_df.head(4)

,route_id,station_code,date,departure_time_utc,executor_capacity_cm3,route_score,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours,num_stops_x,num_stops_y,num_stops,total_packages,packages_per_stop,avg_service_time
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,3313071.0,High,7754.1,12940.9,20695.0,5.748611,119,119,119,276,2.319328,46.887319
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,4247527.0,High,6647.8,18623.8,25271.6,7.019889,106,106,106,199,1.877358,93.586935
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,4247527.0,High,9897.4,18951.1,28848.5,8.013472,128,128,128,212,1.656250,89.391981
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,3313071.0,High,9491.5,15476.3,24967.8,6.935500,142,142,142,241,1.697183,64.217012

In [32]:
route_df['capacity_m3'] = route_df['executor_capacity_cm3']/1000000
route_df.drop(columns='executor_capacity_cm3', inplace=True)
route_df.head()

,route_id,station_code,date,departure_time_utc,route_score,total_travel_duration,total_service_time_duration,ERD_seconds,ERD_hours,num_stops_x,num_stops_y,num_stops,total_packages,packages_per_stop,avg_service_time,capacity_m3
0,RouteID_00143bdd-0a6b-49ec-bb35-36593d303e77,DLA3,2018-07-27,16:02:10,High,7754.1,12940.9,20695.0,5.748611,119,119,119,276,2.319328,46.887319,3.313071
1,RouteID_0016bc70-cb8d-48b0-aa55-8ee50bdcdb59,DSE4,2018-07-28,15:44:41,High,6647.8,18623.8,25271.6,7.019889,106,106,106,199,1.877358,93.586935,4.247527
2,RouteID_001948e9-4675-486d-9ec5-912fd8e0770f,DSE5,2018-08-18,15:32:04,High,9897.4,18951.1,28848.5,8.013472,128,128,128,212,1.656250,89.391981,4.247527
3,RouteID_001b4ee3-c4f2-467f-932b-c85524d1021f,DLA9,2018-08-15,15:09:38,High,9491.5,15476.3,24967.8,6.935500,142,142,142,241,1.697183,64.217012,3.313071
4,RouteID_0021a2aa-780f-460d-b09a-f301709e2523,DLA7,2018-08-05,14:23:26,High,13523.7,14729.7,28253.4,7.848167,155,155,155,219,1.412903,67.258904,3.313071

In [34]:
import os
os.makedirs("data", exist_ok=True)
route_df.to_csv("data/route_dataset.csv", index=False)